## server port
#server.port=8888
#
## contextpath
## spring.application.name=first
#server.servlet.context-path=/first
server:
  port: 8888
  servlet:
    context-path: /first

## encoding
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.force=true
#server.servlet.encoding.enabled=true
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      
##dbms 연결
#spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521:xe
#spring.datasource.dbcp2.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.username=C##testweb
#spring.datasource.password=testweb
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    dbcp2:
      driver-class-name: oracle.jdbc.OracleDriver
    username: C##testweb
    password: testweb
    
## mybatis 연결 설정
## mybatis.config-location=classpath:mybatis-config.xml
#mybatis.mapper-locations=classpath:mappers/*-mapper.xml
#mybatis.type-aliases-package=org.myweb.first.memeber.model.vo, org.myweb.first.board.model.vo, org.myweb.first.notice.model.vo, org.myweb.first.common
#mybatis.configuration.jdbc-type-for-null=NULL
mybatis:
    mapper-locations: classpath:mappers/*-mapper.xml
    type-aliases-package: org.myweb.first.member.model.vo, org.myweb.first.board.model.vo, org.myweb.first.notice.model.vo, org.myweb.first.common
    configuration:
      jdbc-type-for-null: NULL
      
## view: jsp
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
mvc:
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp
    
## fileUpload
#spring.servlet.multipart.max-file-size=1MB
#spring.servlet.multipart.max-request-size=10MB
## file.dir=D:/test/
servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      

#
## 로그 레벨 설정
#logging.level.root=info
logging:
  level:
    root: info
    
## 정상적인 object가 아닐 때 직렬화처리 못하게 설정
#spring.jackson.serialization.fail-on-empty-beans=false
spring  :
  jackson:
    serialization:
      fail-on-empty-beans: false

